spring:
  datasource:
    name: yale-zc
    url: jdbc:mysql://119.23.231.181:3306/yale-zc?useUnicode=true&characterEncoding=utf8&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 6r7Z1z%Q
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      connection-init-sqls: set names utf8mb4;
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: yale2017
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0

server:
  port: 8088
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yale.zc.**.bean
redis:
  user-session-key: REDIS_ZC_USER_SESSION
  sys-user-session-key: REDIS_ZC_SYS_USER_SESSION
  sms-prefix: REDIS_SMS
  sms-protection-prefix: REDIS_ZC_SMS_PROTECTION
  session-expire: 2592000
  sms-expire: 1800
  sms-protection-expire: 40
  sms-validate: SMS_8125152
  sms-notify-validate: SMS_115125114
weixin:
  appid: wx35394d582904abfa
  appsecret: 5deffe286b6ecc7f093667de25bdb13a
  oauth:
    auth-url: https://open.weixin.qq.com/connect/oauth2/authorize?appid=APPID&redirect_uri=REDIRECT_URI?refereeId=REFEREEID&response_type=code&scope=SCOPE&state=STATE#wechat_redirect
    scope: snsapi_userinfo
    callback-url: https://rest.fanggongxin.net/weixin/callback
    token-url: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code
    info-url: https://api.weixin.qq.com/sns/userinfo?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN
    oauth-redirect-url: https://www.fanggongxin.net/?token=
  share:
    access-token-url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=SECRET
    ticket-url: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=ACCESS_TOKEN&type=jsapi
qiniu:
  ak: Nwn_zTH3ac2T6Swu3MhQe39Nk7efWiK2ZmoNVcZo
  sk: EnM2r-WYJFdHhYapQQ8_uSqbHh0ICJxofCBPKQJ5
  bucket: yale-tietie
  callback: https://rest.fanggongxin.net/qiniu/callback
  domain: http://onzb85cov.bkt.clouddn.com
  body: "{\"key\":\"$(key)\",\"hash\":\"$(etag)\",\"bucket\":\"$(bucket)\",\"fsize\":$(fsize)}"
  qrcodeurl: https://www.fanggongxin.net?useId=
  qrcodetemppath: /tmp/temp

